DROP TABLE IF EXISTS EMOTIONS;

CREATE TABLE EMOTIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '아이디',
    CONTENT TEXT NOT NULL COMMENT '내용',
    SUBJECT VARCHAR(100) COMMENT '주제',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    REG_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
    MODI_DTM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시'
);
COMMENT ON TABLE EMOTIONS IS '감정 테이블';